// 教AI导航 · 采集块（agent 自动收集，人工补 SOP）
// -----------------------------------------------------------------------------
// 来源：扮演"采集 agent"，对公开可访问的 K12 教育 AI 产品做一轮盘点。
// 每条均经 WebSearch 核实官方 URL（2026-08-04）。
// 信任分级（见 memory 2026-08-04「数据来源方案修订」）：
//   - agent 填写：name / url / tagline / platform / pricing / scenes / subjects / roles / alts / pros / cons
//   - agent 填写（场景推导）：compliance —— 按 scenes/roles 推导的「使用合规护栏」，
//       与 front/data.ts 中 12 条 curated 工具同一口径（隐私/适龄/版权/退费等提示），非公司法律资质。
//   - 占位（留待人工）：logo（首字）、color（品牌色近似）、rating=0（未评）
//   - status 由 seed.ts 统一置 "draft"（软闸，未人工审核不公开）
// 分类纪律：scenes/subjects/roles 严格锁死 front/data.ts 的已知枚举（8 scene / 4 role），
//           任何 agent 自创分类一律丢弃，否则会断前端筛选。
// paths:[] —— 采集阶段只落产品事实，SOP 由人工基于工具后续编辑。
// -----------------------------------------------------------------------------
import type { Tool } from "../../front/src/lib/data";

export const COLLECTED_TOOLS: Tool[] = [
  {
    slug: "doubao",
    name: "豆包",
    logo: "豆",
    color: "#2f6bff",
    tagline: "字节跳动出品的中文全能 AI 助手",
    url: "https://doubao.com",
    roles: ["老师", "学生", "家长"],
    scenes: ["beikeguihua", "kejian", "jiaxiao", "zuoye"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页 / APP / 插件",
    rating: 4.6,
    pros: ["中文语感自然", "支持语音对话", "免费额度充足"],
    cons: ["长文易跑题", "学科深度有限"],
    compliance: "请勿上传含学生真实姓名、肖像的隐私内容；建议学校统一开通教育版账号并制定使用规范。",
    alts: ["deepseek", "glm"],
    paths: [
      {
        title: "用豆包做课堂导入（配图）",
        summary: "情境提问 + AI 配图，3 分钟搞定一节课的开场。",
        estMinutes: 8,
        level: "入门",
        forRole: "老师",
        usageId: "u1",
        steps: [
          {
            goal: "用贴近生活的情境把学生带进课文，并拿到可直接生图的画面描述",
            action: "让豆包生成情境化导入语 + 生图描述",
            prompt:
              "你是一名{{学段学科}}老师，请为{{课文}}设计一段约 2 分钟的课堂导入：先抛一个贴近学生生活的问题，再给出可用于 AI 生图的画面描述（含构图与色调）。",
            outputSample:
              "导入语：「同学们，你们眼中的春天是什么样子的？是楼下草地冒出的第一抹绿，还是窗外悄然攀上的藤蔓……」\n生图描述：暖色调田野，远处淡青山峦，近景一枝初绽的桃花，光影柔和，适合投屏。",
            media: { type: "image", label: "课堂导入配图示意（AI 生成）" },
            tip: "提示词先写「角色 + 任务 + 约束」，豆包更听话；把 {{课文}} 换成这周要讲的篇目即可整套复用。",
          },
          {
            goal: "把文字描述变成可投屏的画面",
            action: "把生图描述丢进生图工具出图并投屏",
            prompt: "",
            outputSample: "一张可直接投屏的导入配图（建议用即梦 / 妙鸭等生图工具，按上面的描述生成）。",
            pitfall: "避免生成带具体校名、班牌的图片，防止信息泄露。",
            tip: "投屏前用班级大屏预览一次，确认分辨率与配色适合后排观看。",
          },
        ],
      },
      {
        title: "用豆包写家校班级话术",
        summary: "先肯定孩子再提建议，生成温和得体的家校沟通话术。",
        estMinutes: 5,
        level: "入门",
        forRole: "老师",
        steps: [
          {
            goal: "先肯定孩子，再温和地传递需改进的信息，语气不伤人",
            action: "说明学生情况与沟通目的",
            prompt:
              "请以班主任口吻，给一位{{学科}}作业连续缺交的学生家长写一段微信：先肯定孩子优点，再委婉说明情况并给出可执行的改进建议，语气温和。",
            outputSample:
              "（示例）XX 妈妈好，XX 最近课堂上思考很积极，这点特别好；不过数学作业已连续两次未交，想和您一起帮孩子把节奏找回来——建议每天放学先完成一科作业再玩，有问题随时找我。",
            pitfall: "涉及学生负面评价时注意措辞，并保留沟通记录。",
            tip: "把「先肯定后建议」的结构固定下来，同类沟通只需替换学生姓名与学科，能大幅提速。",
          },
        ],
      },
    ],
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    logo: "DS",
    color: "#4d6bfe",
    tagline: "深度推理大模型，擅长逻辑与解题",
    url: "https://deepseek.com",
    roles: ["老师", "学生"],
    scenes: ["zuoye", "xueqing", "keti", "zixue"],
    subjects: ["数学"],
    pricing: "Free",
    platform: "网页 / APP / API",
    rating: 4.7,
    pros: ["推理能力强", "完全免费", "支持长上下文"],
    cons: ["高峰期易繁忙", "中文润色稍弱"],
    compliance: "出题涉及考试公平，建议仅用于日常练习与复习，不用于正式测验原题生成。",
    alts: ["kimi", "tongyi"],
    paths: [
      {
        title: "用 DeepSeek 出一套初三数学期中卷",
        summary: "细目表 → 分层命题 → 评分标准，附合规卷首语，一次出齐。",
        estMinutes: 25,
        level: "进阶",
        forRole: "老师",
        usageId: "u2",
        steps: [
          {
            goal: "先定结构与难度分布，避免想到哪出到哪",
            action: "明确范围与难度，生成双向细目表",
            prompt:
              "你是{{年级}}{{学科}}备课组长。请按{{章节列表}}，出一份{{考试名称}}双向细目表：题型、分值、难度（易:中:难=6:3:1）、对应知识点。",
            outputSample:
              "细目表（节选）：选择题 10×3=30 分（易 6 / 中 3 / 难 1）；填空 4×4=16 分……知识点覆盖：一元二次方程 30%、二次函数 40%、旋转 15%、圆 15%。",
            media: { type: "file", label: "期中卷命题细目表.md" },
            tip: "先让模型输出细目表再出题，能避免知识点重复；难度比例可按班级实际调整。",
            branch: [
              { when: "时间紧，想先发练习", then: "只做步骤 1 + 2（细目表 + 基础题）即可先发" },
              { when: "班级基础偏弱", then: "把难度比例调到 易:中:难 = 7:2:1" },
            ],
          },
          {
            goal: "先稳住基础分，保证知识点覆盖面",
            action: "按细目表生成基础题",
            prompt: "基于上面的细目表，先生成「容易」档的 12 道选择题与 4 道填空题，附答案与解析要点。",
            outputSample: "Q1 …… 答案：C。解析：考查一元二次方程根的判别，Δ>0 有两不等实根……",
            tip: "基础题占比最大，务必逐题核对答案，这步错了后面全错。",
          },
          {
            goal: "拉开区分度，并给出可操作的评分尺度",
            action: "生成中档与压轴题",
            prompt: "再生成 4 道中等解答题（含过程分步骤）和 1 道压轴综合题，给出评分标准。",
            outputSample:
              "解答题 3：…… 评分：步骤①2 分、②3 分、③3 分、结论 2 分，共 10 分。",
            pitfall: "务必人工核对答案与知识点覆盖，避免超纲或重复。",
            tip: "压轴题要求学生写完整过程，评分标准按步骤给分更公平。",
          },
          {
            goal: "补一段合规说明，守住考试公平底线",
            action: "生成卷首语与合规说明",
            prompt: "写一段卷首语，提醒学生诚信作答、本卷仅用于阶段练习。",
            outputSample:
              "卷首语：本卷为{{年级}}{{学科}}{{考试名称}}阶段练习，请诚信独立作答；如有疑问课后答疑，勿在考场交流。",
            media: { type: "file", label: "试卷卷首语（合规）.md" },
            tip: "卷首语用中性、鼓励的措辞，别写成批评。",
          },
        ],
      },
      {
        title: "用 DeepSeek 做错题归因",
        summary: "粘贴错题即可拿到错因分析与同类变式题，讲评更高效。",
        estMinutes: 6,
        level: "入门",
        forRole: "老师",
        steps: [
          {
            goal: "找到错在哪、为什么错，并给同类题巩固",
            action: "粘贴错题请其归因",
            prompt: "下面是一道学生常错的{{知识点}}题，请分析典型错误原因，并给出 2 道同类变式题用于巩固。",
            outputSample:
              "典型错因：把{{知识点}}的符号规则记反，导致……变式 1：…… 变式 2：……（均附答案与易错点提示）。",
            tip: "粘贴错题时连「学生的错误答案」一起给，归因才准。",
          },
        ],
      },
    ],
  },
  {
    slug: "glm",
    name: "智谱 GLM",
    logo: "GLM",
    color: "#7c3aed",
    tagline: "国产大模型，文档与 Agent 能力强",
    url: "https://zhipuai.cn",
    roles: ["老师", "学生"],
    scenes: ["keti", "beikeguihua", "xueqing"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页 / API",
    rating: 4.5,
    pros: ["长文档处理稳", "工具调用成熟", "支持智能体"],
    cons: ["免费额度有限", "界面偏专业"],
    compliance: "上传课题资料时注意脱敏；生成的申报书需人工把关学术规范。",
    alts: ["kimi", "deepseek"],
    paths: [
      {
        title: "用 GLM 写课题申报书框架",
        summary: "标准框架 + 逐节扩写，课题申报书骨架一次成型。",
        estMinutes: 20,
        level: "进阶",
        forRole: "老师",
        usageId: "u9",
        steps: [
          {
            goal: "先有骨架再填肉，避免结构遗漏",
            action: "给研究方向让其列框架",
            prompt:
              "我正在申报一项{{级别}}课题：{{课题名称}}。请输出申报书标准框架（问题提出、文献综述、研究目标、内容、方法、创新点、预期成果）。",
            outputSample:
              "一、问题提出：…… 二、文献综述：…… 三、研究目标：…… 四、研究内容：…… 五、研究方法：…… 六、创新点：…… 七、预期成果：……（七节完整骨架）。",
            pitfall: "框架仅为脚手架，核心论点须由教师原创。",
            tip: "框架出来后，先把「创新点」想清楚再扩写，避免后期返工。",
          },
          {
            goal: "逐节落地，便于专家审阅",
            action: "逐节扩写并校验",
            prompt: "请就「研究目标」一节扩写 300 字，语言学术化、可考核。",
            outputSample:
              "研究目标：构建{{学科}}{{主题}}的评价框架，形成可复制的校本案例 3 个，发表相关论文 1 篇。",
            tip: "扩写时给明确字数（如 300 字）和语气（学术化），输出更可控。",
          },
        ],
      },
    ],
  },
  {
    slug: "kimi",
    name: "Kimi",
    logo: "Ki",
    color: "#0ea5e9",
    tagline: "超长上下文，擅长读文献与整理",
    url: "https://kimi.moonshot.cn",
    roles: ["老师", "学生"],
    scenes: ["keti", "zixue", "xueqing"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页 / APP",
    rating: 4.6,
    pros: ["长文档碾压", "摘要精准", "联网检索"],
    cons: ["深度推理一般", "高峰期限速"],
    compliance: "上传文献注意版权；引用须核对原文页码。",
    alts: ["glm", "deepseek"],
    paths: [
      {
        title: "用 Kimi 整理长篇文献",
        summary: "上传 PDF 出结构化卡片，多篇对比即可写综述。",
        estMinutes: 15,
        level: "进阶",
        forRole: "老师",
        usageId: "u6",
        steps: [
          {
            goal: "把一篇长文压缩成可复用、能直接进课件的知识卡片",
            action: "上传 PDF 让其做结构化摘要",
            prompt:
              "请阅读这篇论文，输出：①研究问题 ②方法 ③主要结论 ④可迁移到{{学段}}教学的 3 个启示。用表格呈现。",
            outputSample:
              "研究问题：…… 方法：…… 主要结论：…… 教学启示1：…… 启示2：…… 启示3：……",
            tip: "用表格输出便于直接粘进文献管理工具；{{学段}}换成你教的学生群体。",
          },
          {
            goal: "把多篇结论汇成综述雏形",
            action: "对比多篇提炼综述",
            prompt: "把上面{{篇数}}篇摘要对比，找出共识与分歧，帮我起草一段文献综述。",
            outputSample:
              "三篇文献在{{主题}}上共识为……；分歧在于……；综合来看，建议……（综述段初稿）。",
            pitfall: "综述观点需回到原文核对，勿直接照搬生成文本。",
            tip: "综述段务必回原文核对，AI 可能把不同文献的观点混在一起。",
          },
        ],
      },
    ],
  },
  {
    slug: "mistral",
    name: "秘塔写作猫",
    logo: "秘",
    color: "#0d9488",
    tagline: "中文纠错与润色，批改好帮手",
    url: "https://xiezuocat.com",
    roles: ["老师"],
    scenes: ["zuoye"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页 / 插件",
    rating: 4.4,
    pros: ["错别字捕捉强", "润色自然", "批改高效"],
    cons: ["创意弱", "长文需分段"],
    compliance: "仅处理教学文本，勿让学生作文原文外传至公共网络。",
    alts: ["doubao", "wenxin"],
    paths: [
      {
        title: "用秘塔写作猫润色评语",
        summary: "把生硬草稿改成具体、有鼓励性的作业评语。",
        estMinutes: 4,
        level: "入门",
        forRole: "老师",
        usageId: "u5",
        steps: [
          {
            goal: "把生硬草稿改成具体、有鼓励性的评语",
            action: "粘贴学生作业评语草稿",
            prompt: "（在写作猫中粘贴）请把这段评语改得更具体、更有鼓励性，保留「{{要点}}」的要点。",
            outputSample:
              "原：作业完成一般。\n改：你的计算步骤完整、书写工整，尤其第 3 题的思路很清晰；若能把符号细节再留心，会更出色。",
            pitfall: "保留教师个人信息与判断，AI 只做语言优化。",
            tip: "把「要保留的要点」用 {{要点}} 标出，AI 就不会把你的判断改掉。",
          },
        ],
      },
    ],
  },
  {
    slug: "bishun",
    name: "笔神",
    logo: "笔",
    color: "#db2777",
    tagline: "面向学生的 AI 作文辅导",
    url: "https://bishun.com",
    roles: ["学生", "老师"],
    scenes: ["zuoye", "zixue"],
    subjects: ["语文"],
    pricing: "Freemium",
    platform: "网页 / APP",
    rating: 4.3,
    pros: ["作文思路引导", "素材推荐", "批改反馈"],
    cons: ["需防代写", "部分功能付费"],
    compliance: "应设置“启发而非代写”模式，避免学生直接复制成文。",
    alts: ["doubao", "kimi"],
    paths: [
      {
        title: "用笔神改一篇作文",
        summary: "启发式批改指出问题与方向，保护原创而非代写。",
        estMinutes: 7,
        level: "入门",
        forRole: "学生",
        usageId: "u7",
        steps: [
          {
            goal: "启发修改而非代写，保护原创能力",
            action: "提交作文获取批改",
            prompt: "（在笔神中提交）请指出这篇{{文体}}的结构问题与 3 处可优化的描写，并给修改建议，不要直接重写。",
            outputSample:
              "结构问题：开头铺垫过长，建议 2 句切入。\n可优化描写①第 2 段：…… 建议加一处感官细节。\n（共 3 处，均给修改方向，未替写。）",
            pitfall: "产品须引导「改」而非「替写」，保护原创能力。",
            tip: "用「指出问题 + 给方向」而非「重写」，才能真正提升写作能力。",
          },
        ],
      },
    ],
  },
  {
    slug: "gamma",
    name: "Gamma",
    logo: "G",
    color: "#f59e0b",
    tagline: "一句话生成精美演示文稿",
    url: "https://gamma.app",
    roles: ["老师"],
    scenes: ["kejian"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页",
    rating: 4.5,
    pros: ["排版惊艳", "生成快", "可导出 PPT"],
    cons: ["中文偶有瑕疵", "需联网"],
    compliance: "课件中勿出现真实学生信息；导出后请人工核对事实。",
    alts: ["canva", "kejian"],
    paths: [
      {
        title: "用 Gamma 把大纲变课件",
        summary: "输入章节大纲，一键生成可导出 PPT 的精美课件。",
        estMinutes: 10,
        level: "入门",
        forRole: "老师",
        usageId: "u3",
        steps: [
          {
            goal: "从大纲直接拿到版式初稿，省去排版",
            action: "输入章节大纲生成",
            prompt:
              "基于《{{章节}}》一节的教学大纲（概念、证明、例题、应用），生成一套 {{页数}} 页教学课件，风格简洁学术。",
            outputSample:
              "第1页 封面：{{章节}}；第2页 概念；第3页 证明；第4页 例题；……（共 {{页数}} 页，含版式与配图占位）。",
            media: { type: "image", label: "Gamma 课件排版示意" },
            tip: "先给清晰大纲，Gamma 排版才不跑偏；{{页数}} 建议 12–16 页一节为宜。",
          },
          {
            goal: "拿到可分发、可二次编辑的文件",
            action: "调整并导出为 PPT",
            prompt: "",
            outputSample: "可下载的 .pptx 模板（含版式、字体与占位图，导出后按需替换）。",
            media: { type: "file", label: "{{章节}}课件模板.pptx" },
            pitfall: "导出后务必核对例题答案与版式错乱。",
            tip: "导出 PPT 后，重点核对例题答案与图表来源。",
          },
        ],
      },
    ],
  },
  {
    slug: "canva",
    name: "Canva",
    logo: "C",
    color: "#e11d48",
    tagline: "海量模板的视觉设计工具",
    url: "https://canva.com",
    roles: ["老师", "学生"],
    scenes: ["kejian"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页 / APP",
    rating: 4.4,
    pros: ["模板极多", "易上手", "协作方便"],
    cons: ["AI 能力弱于专用", "高级素材付费"],
    compliance: "使用正版素材；学生作品注意肖像权。",
    alts: ["gamma", "jianying"],
    paths: [
      {
        title: "用 Canva 做课堂海报",
        summary: "选教育模板改文字，快速出一张可张贴的活动海报。",
        estMinutes: 6,
        level: "入门",
        forRole: "老师",
        steps: [
          {
            goal: "快速出一张能直接张贴/群发的活动海报",
            action: "选教育模板改文字",
            prompt: "（在 Canva 中）搜索「{{海报主题}}」模板，替换为{{活动信息}}。",
            outputSample:
              "海报设计稿：标题{{活动名称}}、时间{{时间}}、地点{{地点}}、二维码位预留，配色沿用模板。",
            tip: "搜索模板时用「校园 / 活动」关键词，比从空白做起快 5 倍。",
          },
        ],
      },
    ],
  },
  {
    slug: "jianying",
    name: "剪映",
    logo: "剪",
    color: "#111827",
    tagline: "全民易用的视频剪辑与 AI 成片",
    url: "https://capcut.cn",
    roles: ["老师"],
    scenes: ["shijian"],
    subjects: ["综合"],
    pricing: "Free",
    platform: "APP / 桌面",
    rating: 4.5,
    pros: ["免费", "字幕/配音自动化", "模板多"],
    cons: ["精细控制弱", "水印（免费）"],
    compliance: "微课中不得出现未成年学生正面特写而不经授权。",
    alts: ["canva", "gamma"],
    paths: [
      {
        title: "用剪映做一节微课",
        summary: "图文成片 + 字幕精修，零基础产出短视频微课。",
        estMinutes: 15,
        level: "进阶",
        forRole: "老师",
        usageId: "u4",
        steps: [
          {
            goal: "把讲稿变成带配音的初剪，省去录屏",
            action: "用「图文成片」生成初剪",
            prompt: "（剪映 AI）把《{{课题}}》讲解稿生成带配音的短视频初稿。",
            outputSample: "微课初稿：约 {{时长}} 的短视频，自动字幕 + 配音，画面按讲稿分段。",
            media: { type: "video", label: "《{{课题}}》微课演示" },
            tip: "讲稿分段写、每段配一句画面提示，成片更顺。",
            branch: [
              { when: "还没有写讲稿", then: "先用豆包 / 通义把《{{课题}}》讲稿整理成段落，再回来生成" },
            ],
          },
          {
            goal: "核对术语，精修成片",
            action: "加字幕与转场精修",
            prompt: "",
            outputSample: "成片：字幕逐句校准、转场统一、片头片尾补齐。",
            pitfall: "AI 配音可能念错术语，逐句核对字幕。",
            tip: "AI 配音易念错专业术语，务必逐句听一遍字幕。",
          },
        ],
      },
    ],
  },
  {
    slug: "wenxin",
    name: "文心一言",
    logo: "文",
    color: "#2563eb",
    tagline: "百度大模型，中文知识广",
    url: "https://yiyan.baidu.com",
    roles: ["老师", "学生"],
    scenes: ["jiaxiao", "zuoye", "keti"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页 / APP",
    rating: 4.3,
    pros: ["知识面广", "插件丰富", "国产化"],
    cons: ["深度推理一般", "长文偶散"],
    compliance: "家校班级话术需教师把关；学生内容注意适龄。",
    alts: ["doubao", "glm"],
    paths: [
      {
        title: "用文心一言拟家长通知",
        summary: "填活动时间地点议程，一次生成正式亲切的家长通知。",
        estMinutes: 5,
        level: "入门",
        forRole: "老师",
        steps: [
          {
            goal: "正式又不生硬地把关键信息一次说清",
            action: "给出活动信息生成通知",
            prompt:
              "请写一则{{活动名称}}通知：时间{{时间}}、地点{{地点}}、议程含{{议程项}}，语气正式亲切。",
            outputSample:
              "通知：各位家长好，定于{{时间}}在{{地点}}召开{{活动名称}}，议程包括{{议程项}}。敬请拨冗参加，如有疑问联系班主任。",
            tip: "议程项列清楚，家长一眼就知道要准备什么。",
          },
        ],
      },
    ],
  },
  {
    slug: "tongyi",
    name: "通义千问",
    logo: "通",
    color: "#0891b2",
    tagline: "阿里大模型，答疑与多模态",
    url: "https://tongyi.aliyun.com",
    roles: ["学生", "老师"],
    scenes: ["zixue", "beikeguihua"],
    subjects: ["英语"],
    pricing: "Free",
    platform: "网页 / APP",
    rating: 4.4,
    pros: ["免费", "多模态", "英文强"],
    cons: ["复杂推理一般"],
    compliance: "英语口语练习建议学生自主使用，教师定期检查使用记录。",
    alts: ["kimi", "deepseek"],
    paths: [
      {
        title: "用通义做英语答疑",
        summary: "讲思路不讲答案，引导真正理解而非直接抄。",
        estMinutes: 8,
        level: "入门",
        forRole: "学生",
        usageId: "u8",
        steps: [
          {
            goal: "讲清思路而非直接给答案，引导真正理解",
            action: "拍照/输入题目求讲解",
            prompt: "请讲解这道{{题型}}的解题思路，并标注涉及的语法点，不要只给答案。",
            outputSample:
              "思路：先判断本句缺少{{句子成分}}，再结合时态锁定{{语法点}}……语法点：{{语法点}}的用法是……",
            pitfall: "引导学生理解而非直接抄答案。",
            tip: "要求学生「讲思路不讲答案」，可顺带让模型出 1 道同类题自测。",
            branch: [
              { when: "学生基础弱", then: "追加「多给 2 个例句并放慢解释」" },
              { when: "临近考试", then: "追加「按中考真题风格再出 3 题自测」" },
            ],
          },
        ],
      },
    ],
  },
  {
    slug: "wenku",
    name: "文库 AI",
    logo: "库",
    color: "#475569",
    tagline: "百度文库 AI，资料与总结",
    url: "https://wenku.baidu.com",
    roles: ["老师", "学生"],
    scenes: ["beikeguihua", "zuoye"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "网页",
    rating: 4.2,
    pros: ["资料库大", "总结快", "可出题"],
    cons: ["质量参差", "部分付费"],
    compliance: "引用资料需标注来源；注意版权与适龄。",
    alts: ["kimi", "doubao"],
    paths: [
      {
        title: "用文库 AI 汇总备课资料",
        summary: "零散资料压成备课要点：重点、难点、活动设计。",
        estMinutes: 10,
        level: "入门",
        forRole: "老师",
        steps: [
          {
            goal: "把零散资料压成可直接用的备课要点",
            action: "上传/检索资料生成摘要",
            prompt: "请基于检索到的《{{课文或主题}}》教学资料，生成一份 {{时长}} 备课要点（重点、难点、活动设计）。",
            outputSample:
              "备课要点：重点——{{重点}}；难点——{{难点}}；活动——分组探究{{主题}}，用时约 {{活动时长}}。",
            pitfall: "资料真实性需教师核实，勿盲目采信。",
            tip: "检索词加上「教学设计 / 重难点」，资料质量更高。",
          },
        ],
      },
    ],
  },
  {
    slug: "banjiyouhua",
    name: "班级优化大师",
    logo: "班",
    color: "#00b386",
    tagline: "希沃出品，AI 班级管理与学情看板",
    url: "https://care.seewo.com",
    roles: ["老师", "家长"],
    scenes: ["jiaxiao", "xueqing"],
    subjects: ["综合"],
    pricing: "Free",
    platform: "APP / 网页 / 大屏",
    rating: 0,
    pros: ["与希沃硬件打通", "考勤与行为数据可视化", "家长端同步"],
    cons: ["强绑定希沃生态", "高阶分析需学校开通"],
    compliance: "家校沟通话术需教师把关；班级与学情数据注意学生隐私，不公开排名。",
    alts: ["xiaobao", "xiaohe"],
    paths: [],
  },
  {
    slug: "huohua",
    name: "火花思维",
    logo: "火",
    color: "#ff6a00",
    tagline: "在线数学思维训练，动画化互动课",
    url: "https://www.huohua.cn",
    roles: ["学生"],
    scenes: ["zixue", "shijian"],
    subjects: ["数学"],
    pricing: "Paid",
    platform: "APP / 网页",
    rating: 0,
    pros: ["思维可视化强", "小班直播互动", "关卡式进阶"],
    cons: ["偏数理，学科覆盖窄", "付费门槛较高"],
    compliance: "课程适龄，家长合理规划学习节奏；低龄避免过长时间屏幕学习。",
    alts: ["songshuai", "yangcong"],
    paths: [],
  },
  {
    slug: "zhangmen",
    name: "掌门1对1",
    logo: "掌",
    color: "#ff5a5f",
    tagline: "中小学 1 对 1 在线辅导",
    url: "http://www.zhangmen.com/",
    roles: ["学生", "家长"],
    scenes: ["zuoye", "zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "APP / 网页",
    rating: 0,
    pros: ["师资可选", "个性化排课", "家长可旁听"],
    cons: ["客单价高", "师资质量参差"],
    compliance: "选择持证师资；理性购课，看清退费条款与合同细则。",
    alts: ["yuanfudao", "gaotu"],
    paths: [],
  },
  {
    slug: "guangsuxie",
    name: "光速写作",
    logo: "光",
    color: "#2f80ed",
    tagline: "AI 写作与作文批改助手",
    url: "https://guangsuxie.com/",
    roles: ["学生", "老师"],
    scenes: ["zuoye", "kejian"],
    subjects: ["语文"],
    pricing: "Freemium",
    platform: "网页 / APP",
    rating: 0,
    pros: ["作文批改快", "思路启发", "可导出讲义"],
    cons: ["需防学生直接代写", "深度润色需会员"],
    compliance: "设置“启发而非代写”模式，避免学生直接复制成文；课件勿含真实学生信息。",
    alts: ["bishun", "mistral"],
    paths: [],
  },
  {
    slug: "alfadan",
    name: "阿尔法蛋",
    logo: "蛋",
    color: "#ff7a00",
    tagline: "儿童 AI 学习硬件（词典笔/机器人）",
    url: "https://www.toycloud.com/",
    roles: ["学生", "家长"],
    scenes: ["zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "硬件 + APP",
    rating: 0,
    pros: ["离线可用", "护眼护脊设计", "点读识别准"],
    cons: ["硬件一次性投入", "内容更新依赖厂商"],
    compliance: "硬件含适龄内容，家长管控使用时长；语音交互注意儿童隐私。",
    alts: ["readboy", "youxuepai"],
    paths: [],
  },
  {
    slug: "readboy",
    name: "读书郎",
    logo: "读",
    color: "#e60012",
    tagline: "AI 学习机与智慧课堂硬件",
    url: "https://www.readboy.com/",
    roles: ["学生", "家长"],
    scenes: ["zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "硬件 + APP",
    rating: 0,
    pros: ["同步教材资源多", "家长管控到位", "护眼屏"],
    cons: ["硬件成本较高", "系统相对封闭"],
    compliance: "学习机内容适龄；家长设定使用时长，避免沉迷。",
    alts: ["youxuepai", "alfadan"],
    paths: [],
  },
  {
    slug: "youxuepai",
    name: "优学派",
    logo: "优",
    color: "#1677ff",
    tagline: "AI 学生平板与精准学系统",
    url: "https://www.youxuepai.com/",
    roles: ["学生"],
    scenes: ["zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "硬件 + APP",
    rating: 0,
    pros: ["AI 精准学路径", "题库同步教材", "家长端报告"],
    cons: ["硬件绑定", "增值内容付费"],
    compliance: "内容适龄；家长管控时长，保护视力与作息。",
    alts: ["readboy", "iflytekpad"],
    paths: [],
  },
  {
    slug: "jiazhangbang",
    name: "家长帮",
    logo: "长",
    color: "#ff8c00",
    tagline: "K12 家长社区与升学资讯",
    url: "http://www.jzb.com/",
    roles: ["家长"],
    scenes: ["jiaxiao"],
    subjects: ["综合"],
    pricing: "Free",
    platform: "网页 / APP",
    rating: 0,
    pros: ["经验帖丰富", "政策解读及时", "免费"],
    cons: ["广告较多", "信息需甄别"],
    compliance: "社区交流勿泄露孩子真实身份与学校信息；甄别招生广告。",
    alts: ["xiaobao", "banjiyouhua"],
    paths: [],
  },
  {
    slug: "xiaobao",
    name: "校宝在线",
    logo: "宝",
    color: "#1e88e5",
    tagline: "教育 SaaS 与智慧校园管理",
    url: "https://www.xiaobaoonline.com/",
    roles: ["老师", "学校管理员"],
    scenes: ["jiaxiao", "xueqing"],
    subjects: ["综合"],
    pricing: "Enterprise",
    platform: "SaaS / 网页",
    rating: 0,
    pros: ["排课/家校/收费一体化", "机构与学校双场景", "数据看板"],
    cons: ["面向机构采购", "个人家长难直接用"],
    compliance: "校园数据须脱敏；家校通知话术统一审核后发送。",
    alts: ["banjiyouhua"],
    paths: [],
  },
  {
    slug: "banma",
    name: "斑马AI课",
    logo: "斑",
    color: "#ffd400",
    tagline: "猿辅导旗下 AI 启蒙课程",
    url: "https://banmaaike.com",
    roles: ["学生", "家长"],
    scenes: ["zixue", "shijian"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "APP",
    rating: 0,
    pros: ["低龄启蒙体系完整", "动画互动强", "AI 纠音"],
    cons: ["偏低龄", "续费压力"],
    compliance: "启蒙内容适龄；家长陪伴使用，控制屏幕时间。",
    alts: ["guagualong", "ihuman"],
    paths: [],
  },
  {
    slug: "xiaohe",
    name: "小盒科技",
    logo: "盒",
    color: "#ff6b35",
    tagline: "AI 作业与智能练习平台",
    url: "https://hixiaohe.cn/",
    roles: ["老师", "学生", "家长"],
    scenes: ["zuoye", "xueqing"],
    subjects: ["数学"],
    pricing: "Freemium",
    platform: "APP / 网页 / 硬件",
    rating: 0,
    pros: ["作业自动批改", "学情报告三方可见", "覆盖校内同步"],
    cons: ["部分功能付费", "依赖学校部署"],
    compliance: "作业与学情数据仅用于教学改进；向学生/家长展示时注意隐私。",
    alts: ["zuoyebang", "kuaidui"],
    paths: [],
  },
  {
    slug: "songshuai",
    name: "松鼠AI",
    logo: "鼠",
    color: "#6a5acd",
    tagline: "智适应学习系统（AI 一对一）",
    url: "https://www.songshuai.com",
    roles: ["学生"],
    scenes: ["zixue", "xueqing"],
    subjects: ["数学"],
    pricing: "Paid",
    platform: "APP / 网页 / 门店",
    rating: 0,
    pros: ["知识点级诊断", "个性化推题", "学习路径清晰"],
    cons: ["门店模式重", "学科以数理为主"],
    compliance: "自适应内容需教师定期复核进度；避免过度依赖系统诊断。",
    alts: ["huohua", "yangcong"],
    paths: [],
  },
  {
    slug: "yangcong",
    name: "洋葱学园",
    logo: "葱",
    color: "#ff6b6b",
    tagline: "动画微课与 AI 学伴",
    url: "https://yangcongxueyuan.com",
    roles: ["学生", "老师"],
    scenes: ["zixue"],
    subjects: ["数学"],
    pricing: "Freemium",
    platform: "APP / 网页",
    rating: 0,
    pros: ["知识点动画讲解直观", "校内同步好", "老师可布置"],
    cons: ["深度题需会员", "偏理科"],
    compliance: "微课作为辅学，教师须结合课堂；引用数据请核对。",
    alts: ["songshuai", "huohua"],
    paths: [],
  },
  {
    slug: "koolearn",
    name: "新东方在线",
    logo: "新",
    color: "#e4002b",
    tagline: "新东方网课与备考平台",
    url: "https://www.koolearn.com",
    roles: ["学生"],
    scenes: ["zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "APP / 网页",
    rating: 0,
    pros: ["名师资源多", "备考体系成熟", "品牌背书"],
    cons: ["大班为主", "客单价较高"],
    compliance: "选课看清师资与退费规则；网课内容注意版权。",
    alts: ["xueersi", "gaotu"],
    paths: [],
  },
  {
    slug: "tipaipai",
    name: "题拍拍",
    logo: "题",
    color: "#ffcd00",
    tagline: "拍照搜题与解题视频",
    url: "https://tipaipai.com/",
    roles: ["学生", "家长", "老师"],
    scenes: ["zuoye"],
    subjects: ["数学"],
    pricing: "Freemium",
    platform: "APP",
    rating: 0,
    pros: ["拍照秒出解析", "视频讲解覆盖率高", "免费额度足"],
    cons: ["易诱发抄答案", "需引导讲思路"],
    compliance: "提供解题思路而非直接答案，避免助长抄作业；学生数据勿外传。",
    alts: ["zuoyebang", "kuaidui"],
    paths: [],
  },
  {
    slug: "kuaidui",
    name: "快对",
    logo: "快",
    color: "#00c2a8",
    tagline: "作业检查与 AI 答疑",
    url: "https://www.kuaiduizuoye.com/",
    roles: ["学生", "家长", "老师"],
    scenes: ["zuoye"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "APP",
    rating: 0,
    pros: ["整本教辅核对", "AI 答疑快", "覆盖学科广"],
    cons: ["解析质量参差", "部分付费"],
    compliance: "作业检查用于纠错辅导，非代做；隐私数据优先本地处理。",
    alts: ["tipaipai", "zuoyebang"],
    paths: [],
  },
  {
    slug: "xueersi",
    name: "学而思网校",
    logo: "思",
    color: "#ff7a00",
    tagline: "好未来旗下 K12 素养与网课",
    url: "https://www.xueersi.com/",
    roles: ["学生"],
    scenes: ["zixue", "shijian"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "APP / 网页 / 学习机",
    rating: 0,
    pros: ["教研沉淀深", "素养+学科并重", "学习机生态"],
    cons: ["正价课为主", "续报压力"],
    compliance: "选课核对师资与退费；网课内容版权归机构所有。",
    alts: ["koolearn", "gaotu"],
    paths: [],
  },
  {
    slug: "zuoyebang",
    name: "作业帮",
    logo: "帮",
    color: "#ff6a00",
    tagline: "AI 学习神器：搜题/批改/同步",
    url: "https://www.zuoyebang.com/",
    roles: ["学生", "家长", "老师"],
    scenes: ["zuoye", "zixue"],
    subjects: ["综合"],
    pricing: "Freemium",
    platform: "APP / 网页",
    rating: 0,
    pros: ["19 亿题库", "AI 秒批作业", "写作与同步"],
    cons: ["易依赖搜答案", "增值功能付费"],
    compliance: "搜题用于查漏补缺，建议启发式讲解；学生隐私不上云外传。",
    alts: ["tipaipai", "kuaidui"],
    paths: [],
  },
  {
    slug: "yuanfudao",
    name: "猿辅导",
    logo: "猿",
    color: "#ff7a00",
    tagline: "AI 双师直播课与智能练习",
    url: "https://yuanfudao.com",
    roles: ["学生"],
    scenes: ["zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "APP / 网页",
    rating: 0,
    pros: ["AI 沉浸式课堂", "诊断式规划", "品牌强"],
    cons: ["正价课为主", "排课灵活度一般"],
    compliance: "理性购课注意退费；直播内容适龄。",
    alts: ["gaotu", "xueersi"],
    paths: [],
  },
  {
    slug: "gaotu",
    name: "高途",
    logo: "途",
    color: "#2d8cf0",
    tagline: "名师直播课与 1 对 1 规划",
    url: "https://www.gaotu.cn",
    roles: ["学生"],
    scenes: ["zixue"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "APP / 网页",
    rating: 0,
    pros: ["名师阵容强", "1 对 1 规划", "素养+应试"],
    cons: ["正价课为主", "退费规则需看清"],
    compliance: "选课看清师资与退费条款；避免营销冲动消费。",
    alts: ["xueersi", "yuanfudao"],
    paths: [],
  },
  {
    slug: "youdao",
    name: "网易有道",
    logo: "道",
    color: "#d7282f",
    tagline: "子曰大模型驱动的全家桶学习工具",
    url: "https://www.youdao.com",
    roles: ["学生", "老师"],
    scenes: ["zuoye", "zixue"],
    subjects: ["英语"],
    pricing: "Freemium",
    platform: "APP / 硬件 / 网页",
    rating: 0,
    pros: ["词典笔国民级", "有道小P AI 全科助手", "子曰大模型落地早"],
    cons: ["硬件与会员分开付费", "功能分散在多 App"],
    compliance: "翻译/词典结果需核对；作文批改建议启发而非代写。",
    alts: ["tongyi", "kimi"],
    paths: [],
  },
  {
    slug: "iflytekpad",
    name: "讯飞AI学习机",
    logo: "讯",
    color: "#1a73e8",
    tagline: "星火大模型驱动的 1 对 1 精准学",
    url: "https://edu.iflytek.com/solution/family/learning-pad",
    roles: ["学生"],
    scenes: ["zixue", "xueqing"],
    subjects: ["综合"],
    pricing: "Paid",
    platform: "硬件 + APP",
    rating: 0,
    pros: ["星火大模型精准学", "AI 1对1 答疑", "护眼屏认证"],
    cons: ["硬件成本高", "增值内容付费"],
    compliance: "硬件内容适龄；家长管控时长；学情报告教师复核。",
    alts: ["youxuepai", "readboy"],
    paths: [],
  },
  {
    slug: "seewoban",
    name: "希沃白板",
    logo: "沃",
    color: "#00b386",
    tagline: "互动教学与课件制作神器",
    url: "https://easinote.seewo.com/",
    roles: ["老师"],
    scenes: ["kejian", "beikeguihua"],
    subjects: ["综合"],
    pricing: "Free",
    platform: "客户端 / 网页",
    rating: 0,
    pros: ["云课件互通", "学科工具丰富", "课堂活动模板多"],
    cons: ["偏教师端", "高级素材付费"],
    compliance: "课件中勿出现真实学生信息；导出后请人工核对事实。",
    alts: ["gamma", "canva"],
    paths: [],
  },
  {
    slug: "guagualong",
    name: "瓜瓜龙",
    logo: "瓜",
    color: "#ff8a00",
    tagline: "字节旗下多学科 AI 启蒙",
    url: "https://www.ggl.cn",
    roles: ["学生"],
    scenes: ["zixue", "shijian"],
    subjects: ["英语"],
    pricing: "Paid",
    platform: "APP",
    rating: 0,
    pros: ["英语/思维/语文多学科", "AI 录播课", "北美外教"],
    cons: ["偏低龄", "续费压力"],
    compliance: "启蒙内容适龄；业务调整期请确认服务可用性再购课。",
    alts: ["banma", "ihuman"],
    paths: [],
  },
  {
    slug: "ihuman",
    name: "洪恩",
    logo: "恩",
    color: "#ff5a5f",
    tagline: "纽交所上市儿童启蒙品牌",
    url: "https://www.ihuman.com",
    roles: ["学生"],
    scenes: ["zixue", "shijian"],
    subjects: ["语文"],
    pricing: "Freemium",
    platform: "APP / 硬件",
    rating: 0,
    pros: ["识字/拼音/思维体系全", "牛津树分级阅读", "内容精致"],
    cons: ["内容分散多 App", "部分付费"],
    compliance: "内容适龄；家长陪伴，控制屏幕时间。",
    alts: ["guagualong", "banma"],
    paths: [],
  },
  {
    slug: "codemao",
    name: "编程猫",
    logo: "猫",
    color: "#ffcf00",
    tagline: "青少年编程与 AI 编创教育",
    url: "https://www.codemao.cn/",
    roles: ["学生"],
    scenes: ["shijian", "keti", "zixue"],
    subjects: ["编程"],
    pricing: "Freemium",
    platform: "APP / 网页 / 校园版",
    rating: 0,
    pros: ["图形化到 Python 全路径", "Kitten 融入 AI 功能", "赛事体系"],
    cons: ["系统课付费", "需家长引导"],
    compliance: "鼓励原创创作而非照搬；账号与作品注意安全。",
    alts: ["hetao"],
    paths: [],
  },
  {
    slug: "hetao",
    name: "核桃编程",
    logo: "核",
    color: "#ff7a00",
    tagline: "AI 人机双师少儿编程",
    url: "https://www.hetao101.com",
    roles: ["学生"],
    scenes: ["shijian", "zixue"],
    subjects: ["编程"],
    pricing: "Paid",
    platform: "APP / 网页",
    rating: 0,
    pros: ["十级进阶体系", "AI 人机双师", "家长端学情反馈"],
    cons: ["正价课为主", "续报压力"],
    compliance: "项目式学习鼓励独立思考；注意账号隐私。",
    alts: ["codemao"],
    paths: [],
  },
  {
    slug: "xiaoyuan",
    name: "小猿口算",
    logo: "算",
    color: "#ff6a00",
    tagline: "猿辅导旗下拍照秒批作业（小猿AI）",
    url: "https://www.xiaoyuankousuan.com",
    roles: ["学生", "家长", "老师"],
    scenes: ["zuoye"],
    subjects: ["数学"],
    pricing: "Freemium",
    platform: "APP",
    rating: 0,
    pros: ["口算识别准（99.9%+）", "全班作业一键批改", "免费额度足"],
    cons: ["升级后功能分散", "需引导讲思路"],
    compliance: "口算练习用于巩固，避免机械刷题；数据隐私注意。",
    alts: ["tipaipai", "kuaidui"],
    paths: [],
  },
  {
    slug: "kaishu",
    name: "凯叔讲故事",
    logo: "凯",
    color: "#ff8c00",
    tagline: "0-12 岁高品质原创儿童内容",
    url: "https://www.kaishustory.com/index.html",
    roles: ["学生", "家长"],
    scenes: ["zixue", "shijian"],
    subjects: ["语文"],
    pricing: "Freemium",
    platform: "APP / 硬件 / 图书",
    rating: 0,
    pros: ["国学/名著/科普音频全", "分龄推荐", "家长信赖"],
    cons: ["深度内容付费", "偏听读非互动"],
    compliance: "音频内容适龄；低龄使用家长陪伴，控制时长。",
    alts: ["ihuman", "guagualong"],
    paths: [],
  },
  {
    slug: "shaonian",
    name: "少年得到",
    logo: "少",
    color: "#2f6fed",
    tagline: "7-15 岁素养与表达力课程",
    url: "https://www.igetcool.com/",
    roles: ["学生"],
    scenes: ["zixue"],
    subjects: ["语文"],
    pricing: "Freemium",
    platform: "APP",
    rating: 0,
    pros: ["名师大家音频课", "泉灵的表达素养课", "通识拓展"],
    cons: ["偏音频课", "系统性需自规划"],
    compliance: "课程内容适龄；理性订阅，注意退费。",
    alts: ["kaishu", "youdao"],
    paths: [],
  },
];
